configfile: 'config.json'

rule all:
    input:
        'GSE130399_GSM3737490-GSM3737495_Adult_Cerebrail_Cortex.tar.gz',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA/genes.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA/matrix.mtx',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA/barcodes.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA/peaks.bed',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA/barcodes.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA/matrix.mtx',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA/genes.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA/features.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA/features.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA_filtered/barcodes.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA_filtered/matrix.mtx',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA_filtered/features.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA_filtered/barcodes.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA_filtered/matrix.mtx',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA_filtered/features.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA_filtered/metrics.csv',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA_filtered/metrics.csv'

# download data from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE130399
rule downloadData:
    output:
        'GSE130399_GSM3737490-GSM3737495_Adult_Cerebrail_Cortex.tar.gz'
    shell:
        ''' wget -nc 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE130399&format=file&file=GSE130399%5FGSM3737490%2DGSM3737495%5FAdult%5FCerebrail%5FCortex%2Etar%2Egz' \
            -O {output}
        '''

rule extract:
    input:
        'GSE130399_GSM3737490-GSM3737495_Adult_Cerebrail_Cortex.tar.gz'
    output:
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA/genes.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA/matrix.mtx',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA/barcodes.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA/peaks.bed',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA/barcodes.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA/matrix.mtx',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA/genes.tsv',
    shell:
        ''' tar zxvf {input}
        '''

rule prepareFiles:
    input:
        dna='Adult_Cerebrail_Cortex/Adult_CTX_DNA/genes.tsv',
        rna='Adult_Cerebrail_Cortex/Adult_CTX_RNA/genes.tsv'
    output:
        dna='Adult_Cerebrail_Cortex/Adult_CTX_DNA/features.tsv',
        rna='Adult_Cerebrail_Cortex/Adult_CTX_RNA/features.tsv'
    shell:
        ''' ln -s genes.tsv {output.dna}
            ln -s genes.tsv {output.rna}
        '''

# use the last 10% of barcodes to definte emptydrops
rule fileterCellDNA:
    input:
        pg=config['star_bin'],
        bc='Adult_Cerebrail_Cortex/Adult_CTX_DNA/barcodes.tsv',
        mtx='Adult_Cerebrail_Cortex/Adult_CTX_DNA/matrix.mtx',
        ft='Adult_Cerebrail_Cortex/Adult_CTX_DNA/features.tsv'
    output:
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA_filtered/barcodes.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA_filtered/matrix.mtx',
        'Adult_Cerebrail_Cortex/Adult_CTX_DNA_filtered/features.tsv'
    shell:
        ''' num_abc=$(wc -l {input.bc} | cut -f 1 -d ' ')
            aidx=$(echo "${{num_abc}}*0.9" | bc | cut -f 1 -d '.')
            {input.pg} --runMode soloCellFiltering \
            Adult_Cerebrail_Cortex/Adult_CTX_DNA/ \
            Adult_Cerebrail_Cortex/Adult_CTX_DNA_filtered/ \
            --soloCellFilter EmptyDrops_CR \
            3000 0.99 10 ${{aidx}} ${{num_abc}} 200 0.01 20000 0.01 10000
        '''

# use the last 10% of barcodes to definte emptydrops
rule filterCellRNA:
    input:
        pg=config['star_bin'],
        bc='Adult_Cerebrail_Cortex/Adult_CTX_RNA/barcodes.tsv',
        mtx='Adult_Cerebrail_Cortex/Adult_CTX_RNA/matrix.mtx',
        ft='Adult_Cerebrail_Cortex/Adult_CTX_RNA/features.tsv'
    output:
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA_filtered/barcodes.tsv',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA_filtered/matrix.mtx',
        'Adult_Cerebrail_Cortex/Adult_CTX_RNA_filtered/features.tsv'
    shell:
        ''' num_rbc=$(wc -l {input.bc} | cut -f 1 -d ' ')
            ridx=$(echo "${{num_rbc}}*0.9" | bc | cut -f 1 -d '.')
            {input.pg} --runMode soloCellFiltering \
            Adult_Cerebrail_Cortex/Adult_CTX_RNA/ \
            Adult_Cerebrail_Cortex/Adult_CTX_RNA_filtered/ \
            --soloCellFilter EmptyDrops_CR \
            3000 0.99 10 ${{ridx}} ${{num_rbc}} 200 0.01 20000 0.01 10000
        '''

rule getMetrics:
    input:
        dnabc='Adult_Cerebrail_Cortex/Adult_CTX_DNA/barcodes.tsv',
        dnamtx='Adult_Cerebrail_Cortex/Adult_CTX_DNA_filtered/matrix.mtx',
        rnabc='Adult_Cerebrail_Cortex/Adult_CTX_RNA/barcodes.tsv',
        rnamtx='Adult_Cerebrail_Cortex/Adult_CTX_RNA_filtered/matrix.mtx'
    output:
        dna='Adult_Cerebrail_Cortex/Adult_CTX_DNA_filtered/metrics.csv',
        rna='Adult_Cerebrail_Cortex/Adult_CTX_RNA_filtered/metrics.csv'
    shell:
        ''' ../../scripts/output_qc_mtx {input.dnamtx} {input.dnabc} {output.dna}
            ../../scripts/output_qc_mtx {input.rnamtx} {input.rnabc} {output.rna}
        '''
