configfile: 'config.json'

rule all:
    input:
        '../../e18_mouse_brain_fresh_5k_fastqs.tar',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L001_I1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L001_R1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L001_R2_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L001_R3_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L002_I1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L002_R1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L002_R2_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L002_R3_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L001_I1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L001_I2_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L001_R1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L001_R2_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L002_I1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L002_I2_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L002_R1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L002_R2_001.fastq.gz',
        '../original_data/e18_mouse_brain_fresh_5k_S1_L001_R1_001.fastq.gz',
        '../original_data/e18_mouse_brain_fresh_5k_S1_L001_R2_001.fastq.gz',
        '../original_data/e18_mouse_brain_fresh_5k_S1_L002_R1_001.fastq.gz',
        '../original_data/e18_mouse_brain_fresh_5k_S1_L002_R2_001.fastq.gz',
        'outs/Solo.out/Gene/filtered/barcodes.tsv',
        'outs/Solo.out/Gene/filtered/features.tsv',
        'outs/Solo.out/Gene/filtered/matrix.mtx',
        'outs/Aligned.sortedByCoord.out.bam',
        'outs/Solo.out/Gene/filtered/metrics.csv'

rule downloadFrom10XG:
    input:
        '../../fq_url.txt'
    output:
        '../../e18_mouse_brain_fresh_5k_fastqs.tar'
    shell:
        ''' wget -nc -P ../../ -i {input}
        '''

rule extractFiles:
    input:
        '../../e18_mouse_brain_fresh_5k_fastqs.tar'
    output:
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L001_I1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L001_R1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L001_R2_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L001_R3_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L002_I1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L002_R1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L002_R2_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/atac/e18_mouse_brain_fresh_5k_S1_L002_R3_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L001_I1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L001_I2_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L001_R1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L001_R2_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L002_I1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L002_I2_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L002_R1_001.fastq.gz',
        '../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L002_R2_001.fastq.gz'
    shell:
        ''' tar xvf {input} -C ../../
        '''

rule collectRNAFiles:
    input:
        l1r1='../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L001_R1_001.fastq.gz',
        l1r2='../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L001_R2_001.fastq.gz',
        l2r1='../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L002_R1_001.fastq.gz',
        l2r2='../../e18_mouse_brain_fresh_5k/gex/e18_mouse_brain_fresh_5k_S1_L002_R2_001.fastq.gz'
    output:
        l1r1='../original_data/e18_mouse_brain_fresh_5k_S1_L001_R1_001.fastq.gz',
        l1r2='../original_data/e18_mouse_brain_fresh_5k_S1_L001_R2_001.fastq.gz',
        l2r1='../original_data/e18_mouse_brain_fresh_5k_S1_L002_R1_001.fastq.gz',
        l2r2='../original_data/e18_mouse_brain_fresh_5k_S1_L002_R2_001.fastq.gz'
    shell:
        ''' ln -s {input.l1r1} {output.l1r1}
            ln -s {input.l1r2} {output.l1r2}
            ln -s {input.l2r1} {output.l2r1}
            ln -s {input.l2r2} {output.l2r2}
        '''

rule star:
    input:
        pg=config['star_bin'],
        l1r1='../original_data/e18_mouse_brain_fresh_5k_S1_L001_R1_001.fastq.gz',
        l1r2='../original_data/e18_mouse_brain_fresh_5k_S1_L001_R2_001.fastq.gz',
        l2r1='../original_data/e18_mouse_brain_fresh_5k_S1_L002_R1_001.fastq.gz',
        l2r2='../original_data/e18_mouse_brain_fresh_5k_S1_L002_R2_001.fastq.gz',
        wl='../../../gex_737K-arc-v1.txt'
    output:
        'outs/Solo.out/Gene/filtered/barcodes.tsv',
        'outs/Solo.out/Gene/filtered/features.tsv',
        'outs/Solo.out/Gene/filtered/matrix.mtx',
        'outs/Aligned.sortedByCoord.out.bam'
    params:
        idx=config['star_idx']
    threads: 40
    shell:
        ''' {input.pg} --genomeDir {params.idx} --outFileNamePrefix ./outs/ \
            --readFilesCommand zcat \
            --readFilesIn {input.l1r2},{input.l2r2} {input.l1r1},{input.l2r1} \
            --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 12 \
            --soloBarcodeReadLength 0 --soloType CB_UMI_Simple --clip3pNbases 55 \
            --soloCBwhitelist {input.wl} \
            --soloCellFilter EmptyDrops_CR --runThreadN {threads} \
            --outSAMattributes CB UB --outSAMtype BAM SortedByCoordinate
        '''

rule getMetrics:
    input:
        bc='outs/Solo.out/Gene/filtered/barcodes.tsv',
        mtx='outs/Solo.out/Gene/filtered/matrix.mtx'
    output:
        'outs/Solo.out/Gene/filtered/metrics.csv'
    shell:
        ''' ../../../../scripts/output_qc_mtx {input.mtx} {input.bc} {output}
        '''
