configfile: 'config.json'

rule all:
    input:
        '../../pbmc_unsorted_3k_fastqs.tar',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L001_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L001_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L001_R2_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L001_R3_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L002_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L002_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L002_R2_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L002_R3_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L003_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L003_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L003_R2_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L003_R3_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L004_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L004_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L004_R2_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L004_R3_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L003_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L003_I2_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L003_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L003_R2_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L004_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L004_I2_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L004_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L004_R2_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L001_R1_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L001_R2_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L001_R3_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L002_R1_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L002_R2_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L002_R3_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L003_R1_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L003_R2_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L003_R3_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L004_R1_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L004_R2_001.fastq.gz',
        '../original_data/pbmc_unsorted_3k_S3_L004_R3_001.fastq.gz',
        'genome.sizes',
        'outs/fragments.tsv.gz',
        'outs/fragments.tsv.gz.tbi',
        'outs/per_cell_barcode_total_fragment_count.tsv',
        'outs/fragment_size_distribution.tsv',
        'outs/reads.bed.gz',
        'macs2_pk/aggregate_peaks.narrowPeak',
        'macs2_pk/aggregate_peaks_formatted.bed',
        'outs/peak_read_ov.tsv.gz',
        'outs/raw_mtx/barcodes.tsv',
        'outs/raw_mtx/peaks.bed',
        'outs/raw_mtx/matrix.mtx',
        'outs/raw_mtx/features.tsv',
        'outs/filtered_mtx/barcodes.tsv',
        'outs/filtered_mtx/matrix.mtx',
        'outs/filtered_mtx/features.tsv',
        'outs/filtered_mtx/metrics.csv'

rule downloadFrom10XG:
    input:
        '../../fq_url.txt'
    output:
        '../../pbmc_unsorted_3k_fastqs.tar'
    shell:
        ''' wget -nc -P ../../ -i {input}
        '''

rule extractFiles:
    input:
        '../../pbmc_unsorted_3k_fastqs.tar'
    output:
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L001_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L001_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L001_R2_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L001_R3_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L002_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L002_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L002_R2_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L002_R3_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L003_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L003_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L003_R2_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L003_R3_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L004_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L004_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L004_R2_001.fastq.gz',
        '../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L004_R3_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L003_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L003_I2_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L003_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L003_R2_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L004_I1_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L004_I2_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L004_R1_001.fastq.gz',
        '../../pbmc_unsorted_3k/gex/pbmc_unsorted_3k_S01_L004_R2_001.fastq.gz',
    shell:
        ''' tar xvf {input} -C ../../
        '''

rule collectATACFiles:
    input:
        l1r1='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L001_R1_001.fastq.gz',
        l1cb='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L001_R2_001.fastq.gz',
        l1r2='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L001_R3_001.fastq.gz',
        l2r1='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L002_R1_001.fastq.gz',
        l2cb='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L002_R2_001.fastq.gz',
        l2r2='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L002_R3_001.fastq.gz',
        l3r1='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L003_R1_001.fastq.gz',
        l3cb='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L003_R2_001.fastq.gz',
        l3r2='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L003_R3_001.fastq.gz',
        l4r1='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L004_R1_001.fastq.gz',
        l4cb='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L004_R2_001.fastq.gz',
        l4r2='../../pbmc_unsorted_3k/atac/pbmc_unsorted_3k_S3_L004_R3_001.fastq.gz'
    output:
        l1r1='../original_data/pbmc_unsorted_3k_S3_L001_R1_001.fastq.gz',
        l1cb='../original_data/pbmc_unsorted_3k_S3_L001_R2_001.fastq.gz',
        l1r2='../original_data/pbmc_unsorted_3k_S3_L001_R3_001.fastq.gz',
        l2r1='../original_data/pbmc_unsorted_3k_S3_L002_R1_001.fastq.gz',
        l2cb='../original_data/pbmc_unsorted_3k_S3_L002_R2_001.fastq.gz',
        l2r2='../original_data/pbmc_unsorted_3k_S3_L002_R3_001.fastq.gz',
        l3r1='../original_data/pbmc_unsorted_3k_S3_L003_R1_001.fastq.gz',
        l3cb='../original_data/pbmc_unsorted_3k_S3_L003_R2_001.fastq.gz',
        l3r2='../original_data/pbmc_unsorted_3k_S3_L003_R3_001.fastq.gz',
        l4r1='../original_data/pbmc_unsorted_3k_S3_L004_R1_001.fastq.gz',
        l4cb='../original_data/pbmc_unsorted_3k_S3_L004_R2_001.fastq.gz',
        l4r2='../original_data/pbmc_unsorted_3k_S3_L004_R3_001.fastq.gz'
    shell:
        ''' ln -s {input.l1r1} {output.l1r1}
            ln -s {input.l1cb} {output.l1cb}
            ln -s {input.l1r2} {output.l1r2}
            ln -s {input.l2r1} {output.l2r1}
            ln -s {input.l2cb} {output.l2cb}
            ln -s {input.l2r2} {output.l2r2}
            ln -s {input.l3r1} {output.l3r1}
            ln -s {input.l3cb} {output.l3cb}
            ln -s {input.l3r2} {output.l3r2}
            ln -s {input.l4r1} {output.l4r1}
            ln -s {input.l4cb} {output.l4cb}
            ln -s {input.l4r2} {output.l4r2}
        '''

rule getGenomeSize:
    input:
        config['chromap_fa']
    output:
        'genome.sizes'
    shell:
        ''' faSize -detailed {input} | sort -k1,1 -k2,2n > {output}
        '''

rule chromap:
    input:
        l1r1='../original_data/pbmc_unsorted_3k_S3_L001_R1_001.fastq.gz',
        l1cb='../original_data/pbmc_unsorted_3k_S3_L001_R2_001.fastq.gz',
        l1r2='../original_data/pbmc_unsorted_3k_S3_L001_R3_001.fastq.gz',
        l2r1='../original_data/pbmc_unsorted_3k_S3_L002_R1_001.fastq.gz',
        l2cb='../original_data/pbmc_unsorted_3k_S3_L002_R2_001.fastq.gz',
        l2r2='../original_data/pbmc_unsorted_3k_S3_L002_R3_001.fastq.gz',
        l3r1='../original_data/pbmc_unsorted_3k_S3_L003_R1_001.fastq.gz',
        l3cb='../original_data/pbmc_unsorted_3k_S3_L003_R2_001.fastq.gz',
        l3r2='../original_data/pbmc_unsorted_3k_S3_L003_R3_001.fastq.gz',
        l4r1='../original_data/pbmc_unsorted_3k_S3_L004_R1_001.fastq.gz',
        l4cb='../original_data/pbmc_unsorted_3k_S3_L004_R2_001.fastq.gz',
        l4r2='../original_data/pbmc_unsorted_3k_S3_L004_R3_001.fastq.gz',
        wl='../../../atac_737K-arc-v1.txt'
    output:
        'outs/fragments.tsv.gz',
        'outs/fragments.tsv.gz.tbi'
    log:
        'logs/chromap.err'
    params:
        idx=config['chromap_idx'],
        fa=config['chromap_fa']
    threads: 40
    shell:
        ''' chromap -t {threads} --preset atac -x {params.idx} -r {params.fa} \
            -1 {input.l1r1},{input.l2r1},{input.l3r1},{input.l4r1} \
            -2 {input.l1r2},{input.l2r2},{input.l3r2},{input.l4r2} \
            -b {input.l1cb},{input.l2cb},{input.l3cb},{input.l4cb} \
            --barcode-whitelist {input.wl} \
            -o outs/fragments.tsv 2> {log}
            bgzip outs/fragments.tsv && \
            tabix -p bed outs/fragments.tsv.gz
        '''

rule fragToReads:
    input:
        frag='outs/fragments.tsv.gz',
        gs='genome.sizes'
    output:
        met='outs/per_cell_barcode_total_fragment_count.tsv',
        bed='outs/reads.bed.gz'
    shell:
        ''' ../../../../scripts/convert_frag_to_reads.py | \
            bedClip stdin {input.gs} stdout | \
            sort -k1,1 -k2,2n | \
            gzip > {output.bed}
        '''

rule peakCalling:
    input:
        'outs/reads.bed.gz'
    output:
        'macs2_pk/aggregate_peaks.narrowPeak'
    log:
        'logs/macs2.err'
    params:
        gs=config['macs2_gsize'],
        broad=config['macs2_bpk'],
        fmt=config['macs2_format'],
        shift=config['macs2_shift']
    shell:
        ''' macs2 callpeak -t {input} -g {params.gs} {params.broad} \
            -f {params.fmt} {params.shift} --keep-dup all \
            -B --SPMR --outdir macs2_pk -n aggregate \
            2> {log}
        '''

rule formatPeak:
    input:
        npk='macs2_pk/aggregate_peaks.narrowPeak',
        bdt=config['bedtools_bin'],
        bl=config['blacklist']
    output:
        'macs2_pk/aggregate_peaks_formatted.bed'
    shell:
        ''' cut -f 1-4 {input.npk} | \
            sed '/chrM/d' | \
            {input.bdt} intersect -a - -b {input.bl} -v | \
            sort -k1,1 -k2,2n > {output}
        '''

rule prepareReadPeaksOVs:
    input:
        bdt=config['bedtools_bin'],
        reads='outs/reads.bed.gz',
        peaks='macs2_pk/aggregate_peaks_formatted.bed',
        gsize='genome.sizes'
    output:
        'outs/peak_read_ov.tsv.gz'
    shell:
        ''' {input.bdt} intersect -a {input.peaks} -b {input.reads} \
            -wo -sorted -g {input.gsize} | sort -k8,8 | \
            {input.bdt} groupby -g 8 -c 4 -o freqdesc | gzip > {output}
        '''

rule generate10xStyleOutput1:
    input:
         peaks='macs2_pk/aggregate_peaks_formatted.bed',
         ov='outs/peak_read_ov.tsv.gz'
    output:
        bc='outs/raw_mtx/barcodes.tsv',
        pk='outs/raw_mtx/peaks.bed'
    shell:
        ''' cut -f 1-3 {input.peaks} > {output.pk}
            zcat {input.ov} | cut -f 1 > {output.bc}
        '''

rule generate10xStyleOutput2:
    input:
        ov='outs/peak_read_ov.tsv.gz',
        bc='outs/raw_mtx/barcodes.tsv',
        peaks='macs2_pk/aggregate_peaks_formatted.bed'
    output:
        'outs/raw_mtx/matrix.mtx'
    script:
        '../../../../scripts/generate_csc_mtx.py'

rule prepareSoloFilter:
    input:
        'outs/raw_mtx/peaks.bed'
    output:
        'outs/raw_mtx/features.tsv'
    shell:
        ''' awk 'BEGIN{{OFS="\t"}}{{print $1 "-" $2 "-" $3, $1 "-" $2 "-" $3}}' \
            {input} > {output}
        '''

rule soloFilterCell:
    input:
        pg=config['star_bin'],
        bc='outs/raw_mtx/barcodes.tsv',
        ct='outs/raw_mtx/matrix.mtx',
        ft='outs/raw_mtx/features.tsv'
    output:
        'outs/filtered_mtx/barcodes.tsv',
        'outs/filtered_mtx/matrix.mtx',
        'outs/filtered_mtx/features.tsv'
    shell:
        ''' {input.pg} --runMode soloCellFiltering \
            outs/raw_mtx outs/filtered_mtx/ \
            --soloCellFilter EmptyDrops_CR
        '''

rule getFragmentSizeDistributionChromap:
    input:
        'outs/fragments.tsv.gz'
    output:
        'outs/fragment_size_distribution.tsv'
    shell:
        ''' echo -e "size\tcount" > {output}
            zcat {input} | sed '/^#/d' | awk '{{print $3-$2}}' | \
            sort | uniq -c | sort -b -k2,2n | \
            awk 'BEGIN{{OFS="\t"}}{{print $2, $1}}' >> {output}
        '''

rule getMetricsChromap:
    input:
        bc='outs/filtered_mtx/barcodes.tsv',
        mtx='outs/filtered_mtx/matrix.mtx'
    output:
        'outs/filtered_mtx/metrics.csv'
    shell:
        ''' ../../../../scripts/output_qc_mtx {input.mtx} {input.bc} {output}
        '''
