configfile: 'config.json'

rule all:
    input:
        '../original_data/E14_Protector_30C_FACS_RNA_I1_001.fastq.gz',
        '../original_data/E14_Protector_30C_FACS_RNA_I2_001.fastq.gz',
        '../original_data/E14_Protector_30C_FACS_RNA_R1_001.fastq.gz',
        '../original_data/E14_Protector_30C_FACS_RNA_R2_001.fastq.gz',
        '../original_data/E14_RiboLock_30C_FACS_RNA_I1_001.fastq.gz',
        '../original_data/E14_RiboLock_30C_FACS_RNA_I2_001.fastq.gz',
        '../original_data/E14_RiboLock_30C_FACS_RNA_R1_001.fastq.gz',
        '../original_data/E14_RiboLock_30C_FACS_RNA_R2_001.fastq.gz',
        '../cb_whitelist.txt',
        '../original_data/E14_Protector_30C_FACS_RNA_CB_UMI.fastq.gz',
        '../original_data/E14_RiboLock_30C_FACS_RNA_CB_UMI.fastq.gz',
        'downsampled_fq/E14_Protector_30C_FACS_RNA_ds_cdna.fq.gz',
        'downsampled_fq/E14_Protector_30C_FACS_RNA_ds_cb_umi.fq.gz',
        'downsampled_fq/E14_RiboLock_30C_FACS_RNA_ds_cdna.fq.gz',
        'downsampled_fq/E14_RiboLock_30C_FACS_RNA_ds_cb_umi.fq.gz',
        'merged_fq/E14_FACS_RNA_ds_cdna.fq.gz',
        'merged_fq/E14_FACS_RNA_ds_cb_umi.fq.gz',
        'outs/Solo.out/Gene/filtered/barcodes.tsv',
        'outs/Solo.out/Gene/filtered/features.tsv',
        'outs/Solo.out/Gene/filtered/matrix.mtx',
        'outs/Aligned.sortedByCoord.out.bam',
        'outs/Solo.out/Gene/filtered/metrics.csv'

rule downloadFromEBI:
    input:
        '../fq_url.txt'
    output:
        '../original_data/E14_Protector_30C_FACS_RNA_I1_001.fastq.gz',
        '../original_data/E14_Protector_30C_FACS_RNA_I2_001.fastq.gz',
        '../original_data/E14_Protector_30C_FACS_RNA_R1_001.fastq.gz',
        '../original_data/E14_Protector_30C_FACS_RNA_R2_001.fastq.gz',
        '../original_data/E14_RiboLock_30C_FACS_RNA_I1_001.fastq.gz',
        '../original_data/E14_RiboLock_30C_FACS_RNA_I2_001.fastq.gz',
        '../original_data/E14_RiboLock_30C_FACS_RNA_R1_001.fastq.gz',
        '../original_data/E14_RiboLock_30C_FACS_RNA_R2_001.fastq.gz'
    shell:
        ''' wget -nc -P ../original_data -i {input}
        '''

rule prepareWhitelist:
    input:
        '../E14_Protector_30C_FACS_RNA_whitelist.txt',
        '../E14_RiboLock_30C_FACS_RNA_whitelist.txt'
    output:
        '../cb_whitelist.txt'
    shell:
        ''' cat {input} > {output}
        '''

rule prepareCBUMI1:
    input:
        i1='../original_data/E14_Protector_30C_FACS_RNA_I1_001.fastq.gz',
        i2='../original_data/E14_Protector_30C_FACS_RNA_I2_001.fastq.gz',
        umi='../original_data/E14_Protector_30C_FACS_RNA_R1_001.fastq.gz'
    output:
        '../original_data/E14_Protector_30C_FACS_RNA_CB_UMI.fastq.gz'
    shell:
        ''' paste <(zcat {input.i1}) <(zcat {input.i2}) <(zcat {input.umi}) | \
            awk -F '\t' '{{if(NR%4==1||NR%4==3) {{print $1}} if(NR%4==2||NR%4==0) {{print $1 $2 substr($3,1,10)}} }}' | \
            gzip > {output}
        '''

rule prepareCBUMI2:
    input:
        i1='../original_data/E14_RiboLock_30C_FACS_RNA_I1_001.fastq.gz',
        i2='../original_data/E14_RiboLock_30C_FACS_RNA_I2_001.fastq.gz',
        umi='../original_data/E14_RiboLock_30C_FACS_RNA_R1_001.fastq.gz'
    output:
        '../original_data/E14_RiboLock_30C_FACS_RNA_CB_UMI.fastq.gz'
    shell:
        ''' paste <(zcat {input.i1}) <(zcat {input.i2}) <(zcat {input.umi}) | \
            awk -F '\t' '{{if(NR%4==1||NR%4==3) {{print $1}} if(NR%4==2||NR%4==0) {{print $1 $2 substr($3,1,10)}} }}' | \
            gzip > {output}
        '''

rule subsample1:
    input:
        cdna='../original_data/E14_Protector_30C_FACS_RNA_R2_001.fastq.gz',
        cb='../original_data/E14_Protector_30C_FACS_RNA_CB_UMI.fastq.gz'
    output:
        cdna='downsampled_fq/E14_Protector_30C_FACS_RNA_ds_cdna.fq.gz',
        cb='downsampled_fq/E14_Protector_30C_FACS_RNA_ds_cb_umi.fq.gz'
    shell:
        ''' seqtk sample -s 42 {input.cdna} 0.32 | gzip > {output.cdna}
            seqtk sample -s 42 {input.cb} 0.32 | gzip > {output.cb}
        '''

rule subsample2:
    input:
        cdna='../original_data/E14_RiboLock_30C_FACS_RNA_R2_001.fastq.gz',
        cb='../original_data/E14_RiboLock_30C_FACS_RNA_CB_UMI.fastq.gz'
    output:
        cdna='downsampled_fq/E14_RiboLock_30C_FACS_RNA_ds_cdna.fq.gz',
        cb='downsampled_fq/E14_RiboLock_30C_FACS_RNA_ds_cb_umi.fq.gz'
    shell:
        ''' seqtk sample -s 42 {input.cdna} 0.33 | gzip > {output.cdna}
            seqtk sample -s 42 {input.cb} 0.33 | gzip > {output.cb}
        '''

rule mergeFq:
    input:
        r1cdna='downsampled_fq/E14_Protector_30C_FACS_RNA_ds_cdna.fq.gz',
        r1cb='downsampled_fq/E14_Protector_30C_FACS_RNA_ds_cb_umi.fq.gz',
        r2cdna='downsampled_fq/E14_RiboLock_30C_FACS_RNA_ds_cdna.fq.gz',
        r2cb='downsampled_fq/E14_RiboLock_30C_FACS_RNA_ds_cb_umi.fq.gz'
    output:
        cdna='merged_fq/E14_FACS_RNA_ds_cdna.fq.gz',
        cb='merged_fq/E14_FACS_RNA_ds_cb_umi.fq.gz'
    shell:
        ''' cat {input.r1cdna} {input.r2cdna} > {output.cdna}
            cat {input.r1cb} {input.r2cb} > {output.cb}
        '''

rule star:
    input:
        pg=config['star_bin'],
        cdna='merged_fq/E14_FACS_RNA_ds_cdna.fq.gz',
        cb='merged_fq/E14_FACS_RNA_ds_cb_umi.fq.gz',
        wl='../cb_whitelist.txt'
    output:
        'outs/Solo.out/Gene/filtered/barcodes.tsv',
        'outs/Solo.out/Gene/filtered/features.tsv',
        'outs/Solo.out/Gene/filtered/matrix.mtx',
        'outs/Aligned.sortedByCoord.out.bam'
    params:
        idx=config['star_idx']
    threads: 40
    shell:
        ''' {input.pg} --genomeDir {params.idx} --outFileNamePrefix ./outs/ \
            --readFilesCommand zcat \
            --readFilesIn {input.cdna} {input.cb} \
            --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 10 \
            --soloType CB_UMI_Simple --clip3pNbases 2 \
            --soloCBwhitelist {input.wl} \
            --soloCellFilter EmptyDrops_CR --runThreadN {threads} \
            --outSAMattributes CB UB --outSAMtype BAM SortedByCoordinate
        '''

rule getMetrics:
    input:
        bc='outs/Solo.out/Gene/filtered/barcodes.tsv',
        mtx='outs/Solo.out/Gene/filtered/matrix.mtx'
    output:
        'outs/Solo.out/Gene/filtered/metrics.csv'
    shell:
        ''' ../../../scripts/output_qc_mtx {input.mtx} {input.bc} {output}
        '''
