configfile: 'config.json'

rule all:
    input:
        '../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_I2_001.fastq.gz',
        '../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_R1_001.fastq.gz',
        '../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_R2_001.fastq.gz',
        '../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_CB_UMI.fastq.gz',
        'downsampled_fq/Mix_HEK293T_NIH3T3_Droplet_RNA_ds_cdna.fq.gz',
        'downsampled_fq/Mix_HEK293T_NIH3T3_Droplet_RNA_ds_cb_umi.fq.gz',
        'outs/Solo.out/Gene/filtered/barcodes.tsv',
        'outs/Solo.out/Gene/filtered/features.tsv',
        'outs/Solo.out/Gene/filtered/matrix.mtx',
        'outs/Aligned.sortedByCoord.out.bam',
        'outs/per_cell_barcode_total_read_count_GRCh38.tsv',
        'outs/per_cell_barcode_total_read_count_mm10.tsv'

rule downloadFromEBI:
    input:
        '../fq_url.txt'
    output:
        '../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_I2_001.fastq.gz'
        '../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_R1_001.fastq.gz',
        '../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_R2_001.fastq.gz',
    shell:
        ''' wget -nc -P ../original_data -i {input}
        '''

rule prepareCBUMI:
    input:
        umi='../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_R2_001.fastq.gz',
        cb='../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_I2_001.fastq.gz',
    output:
        '../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_CB_UMI.fastq.gz'
    shell:
        ''' paste <(zcat {input.cb}) <(zcat {input.umi}) | \
            awk -F '\t' '{{if(NR%4==1||NR%4==3) {{print $1}} if(NR%4==2||NR%4==0) {{print $1 substr($2,1,10)}} }}' | \
            gzip > {output}
        '''

rule subsample1:
    input:
        '../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_R1_001.fastq.gz'
    output:
        'downsampled_fq/Mix_HEK293T_NIH3T3_Droplet_RNA_ds_cdna.fq.gz'
    shell:
        ''' seqtk sample -s 42 {input} 0.4 | gzip > {output}
        '''

rule subsample2:
    input:
        '../original_data/Mix_HEK293T_NIH3T3_Droplet_RNA_S1_L001_CB_UMI.fastq.gz'
    output:
        'downsampled_fq/Mix_HEK293T_NIH3T3_Droplet_RNA_ds_cb_umi.fq.gz'
    shell:
        ''' seqtk sample -s 42 {input} 0.4 | gzip > {output}
        '''

rule star:
    input:
        pg=config['star_bin'],
        cdna='downsampled_fq/Mix_HEK293T_NIH3T3_Droplet_RNA_ds_cdna.fq.gz',
        cb='downsampled_fq/Mix_HEK293T_NIH3T3_Droplet_RNA_ds_cb_umi.fq.gz',
        wl='../../../737K-cratac-v1_rc.txt'
    output:
        'outs/Solo.out/Gene/filtered/barcodes.tsv',
        'outs/Solo.out/Gene/filtered/features.tsv',
        'outs/Solo.out/Gene/filtered/matrix.mtx',
        'outs/Aligned.sortedByCoord.out.bam'
    params:
        idx=config['star_idx']
    threads: 40
    shell:
        ''' {input.pg} --genomeDir {params.idx} --outFileNamePrefix ./outs/ \
            --readFilesCommand zcat --readFilesIn {input.cdna} {input.cb} \
            --soloCBstart 1 --soloCBlen 16 --soloUMIstart 17 --soloUMIlen 10 \
            --soloType CB_UMI_Simple --clip3pNbases 115 \
            --soloCBwhitelist {input.wl} \
            --soloCellFilter EmptyDrops_CR --runThreadN {threads} \
            --outSAMattributes CB UB --outSAMtype BAM SortedByCoordinate
        '''

rule checkNumReadsSpecies:
    input:
        'outs/Aligned.sortedByCoord.out.bam'
    output:
        hs='outs/per_cell_barcode_total_read_count_GRCh38.tsv',
        mm='outs/per_cell_barcode_total_read_count_mm10.tsv'
    shell:
        ''' samtools view -q 30 -F 3844 {input} | \
            grep GRCh38 | grep -oP 'CB:Z:[ACGT]{{16}}' | \
            cut -f 3 -d ':' | sort | uniq -c  | \
            awk 'BEGIN{{OFS="\t"}}{{print $1, $2}}' > {output.hs}
            samtools view -q 30 -F 3844 {input} | \
            grep mm10 | grep -oP 'CB:Z:[ACGT]{{16}}' | \
            cut -f 3 -d ':' | sort | uniq -c  | \
            awk 'BEGIN{{OFS="\t"}}{{print $1, $2}}' > {output.mm}
        '''
